version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_army_community
    restart: always
    environment:
      POSTGRES_DB: army_community
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: Student1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
